In [1]:
import pandas as pd
import geopandas as gpd
from datetime import date
import numpy as np
import re

In [2]:
trash = pd.read_csv('trash_hauler_report_with_lat_lng.csv')

# Data Exploring and Cleaning

In [3]:
trash.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,LONGITUDE,LATITUDE
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,2.0,1.727970e+06,686779.478089,-86.815392,36.217292
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565,-86.838103,36.213470
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571,-86.885562,36.142923
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1.735692e+06,685027.245923,-86.789170,36.212652
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066,-86.874995,36.154861

In [4]:
trash.tail()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,LONGITUDE,LATITUDE
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,32.0,1.781137e+06,632448.551144,-86.633970,36.069130
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,6.0,1.749711e+06,669201.601569,-86.741242,36.169482
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,15.0,1.770293e+06,674936.303809,-86.671647,36.185643
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,32.0,1.785225e+06,627146.400187,-86.620025,36.054637
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,29.0,1.781360e+06,637742.006846,-86.633331,36.083675

In [5]:
trash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20226 entries, 0 to 20225
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    20226 non-null  int64
 1   Date Opened       20226 non-null  object
 2   Request           20226 non-null  object
 3   Description       20195 non-null  object
 4   Incident Address  20217 non-null  object
 5   Zip Code          20151 non-null  float64
 6   Trash Hauler      19325 non-null  object
 7   Trash Route       19279 non-null  object
 8   Council District  20177 non-null  float64
 9   State Plan X      20198 non-null  float64
 10  State Plan Y      20198 non-null  float64
 11  LONGITUDE         20198 non-null  float64
 12  LATITUDE          20198 non-null  float64
dtypes: float64(6), int64(1), object(6)
memory usage: 2.0+ MB

In [6]:
trash.isna().sum()

Request Number        0
Date Opened           0
Request               0
Description          31
Incident Address      9
Zip Code             75
Trash Hauler        901
Trash Route         947
Council District     49
State Plan X         28
State Plan Y         28
LONGITUDE            28
LATITUDE             28
dtype: int64

In [7]:
trash['Zip Code'].isna().sum()

75

In [8]:
trash.nunique()

Request Number      20226
Date Opened           686
Request                 4
Description         12879
Incident Address    14121
Zip Code               28
Trash Hauler            4
Trash Route           173
Council District       35
State Plan X        14243
State Plan Y        14322
LONGITUDE           14303
LATITUDE            14382
dtype: int64

In [9]:
cleantrash = trash.drop(columns = ['State Plan X', 'State Plan Y', 'Council District'])
cleantrash.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,-86.815392,36.217292
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,-86.838103,36.213470
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,-86.885562,36.142923
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,-86.789170,36.212652
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,-86.874995,36.154861

In [10]:
cleantrash.isna().sum()

Request Number        0
Date Opened           0
Request               0
Description          31
Incident Address      9
Zip Code             75
Trash Hauler        901
Trash Route         947
LONGITUDE            28
LATITUDE             28
dtype: int64

In [11]:
cleantrash['Zip Code'].value_counts()

Zip Code
37013.0    2278
37211.0    2248
37205.0    1491
37209.0    1411
37215.0    1404
37207.0    1300
37115.0    1266
37206.0    1217
37208.0    1039
37214.0    1004
37218.0     983
37216.0     841
37217.0     832
37204.0     635
37212.0     601
37210.0     550
37203.0     394
37220.0     289
37027.0     168
37189.0      60
37221.0      48
37219.0      42
37201.0      35
37076.0       5
37138.0       5
37086.0       3
37213.0       1
37228.0       1
Name: count, dtype: int64

In [12]:
cleantrash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20226 entries, 0 to 20225
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    20226 non-null  int64
 1   Date Opened       20226 non-null  object
 2   Request           20226 non-null  object
 3   Description       20195 non-null  object
 4   Incident Address  20217 non-null  object
 5   Zip Code          20151 non-null  float64
 6   Trash Hauler      19325 non-null  object
 7   Trash Route       19279 non-null  object
 8   LONGITUDE         20198 non-null  float64
 9   LATITUDE          20198 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 1.5+ MB

In [13]:
cleantrash['Date Opened'] = pd.to_datetime(cleantrash['Date Opened'], format='%m/%d/%y')
cleantrash.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE
0,25270,2017-11-01,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,-86.815392,36.217292
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,-86.838103,36.213470
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,-86.885562,36.142923
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,-86.789170,36.212652
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,-86.874995,36.154861

In [14]:
cleantrash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20226 entries, 0 to 20225
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    20226 non-null  int64
 1   Date Opened       20226 non-null  datetime64[ns]
 2   Request           20226 non-null  object
 3   Description       20195 non-null  object
 4   Incident Address  20217 non-null  object
 5   Zip Code          20151 non-null  float64
 6   Trash Hauler      19325 non-null  object
 7   Trash Route       19279 non-null  object
 8   LONGITUDE         20198 non-null  float64
 9   LATITUDE          20198 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 1.5+ MB

In [15]:
cleantrash['Trash Hauler'].unique()

array(['RED RIVER', 'WASTE IND', 'METRO', nan, 'Metro'], dtype=object)

In [16]:
cleantrash['Trash Hauler'].value_counts()

Trash Hauler
RED RIVER    14395
METRO         3512
WASTE IND     1350
Metro           68
Name: count, dtype: int64

In [17]:
cleantrash['Trash Hauler'] = cleantrash['Trash Hauler'].replace('Metro', 'METRO')
cleantrash['Trash Hauler'].value_counts()

Trash Hauler
RED RIVER    14395
METRO         3580
WASTE IND     1350
Name: count, dtype: int64

In [18]:
cleantrash = cleantrash.rename(columns = {'Request ' : 'Request'})
cleantrash.columns

Index(['Request Number', 'Date Opened', 'Request', 'Description',
       'Incident Address', 'Zip Code', 'Trash Hauler', 'Trash Route',
       'LONGITUDE', 'LATITUDE'],
      dtype='object')

In [19]:
#cleantrash = cleantrash.dropna(subset='Incident Address')

In [20]:
cleantrash.isna().sum()

Request Number        0
Date Opened           0
Request               0
Description          31
Incident Address      9
Zip Code             75
Trash Hauler        901
Trash Route         947
LONGITUDE            28
LATITUDE             28
dtype: int64

In [21]:
cleantrash = cleantrash.reset_index(drop = True)
cleantrash.tail()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE
20221,267125,2019-11-01,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013.0,RED RIVER,4502,-86.633970,36.069130
20222,267126,2019-11-01,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206.0,METRO,9508,-86.741242,36.169482
20223,267130,2019-11-01,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214.0,RED RIVER,1502,-86.671647,36.185643
20224,267134,2019-11-01,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013.0,RED RIVER,4502,-86.620025,36.054637
20225,267137,2019-11-01,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217.0,RED RIVER,2505,-86.633331,36.083675

In [22]:
cleantrash['Incident Address'] = cleantrash['Incident Address'].str.upper()

cleantrash['Incident Address'].head()

0           3817 CROUCH DR
1    4028 CLARKSVILLE PIKE
2      6528 THUNDERBIRD DR
3     2603 OLD MATTHEWS RD
4            604 CROLEY DR
Name: Incident Address, dtype: object

In [23]:
cleantrash[['Clean Address', 'Addy2']] = cleantrash['Incident Address'].str.split(',', n=1, expand = True)

cleantrash.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address,Addy2
0,25270,2017-11-01,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 CROUCH DR,37207.0,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR,None
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 CLARKSVILLE PIKE,37218.0,RED RIVER,4202,-86.838103,36.213470,4028 CLARKSVILLE PIKE,None
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 THUNDERBIRD DR,37209.0,RED RIVER,4205,-86.885562,36.142923,6528 THUNDERBIRD DR,None
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,missed,2603 OLD MATTHEWS RD,37207.0,WASTE IND,2206,-86.789170,36.212652,2603 OLD MATTHEWS RD,None
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 CROLEY DR,37209.0,RED RIVER,4203,-86.874995,36.154861,604 CROLEY DR,None

In [24]:
cleantrash.tail()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address,Addy2
20221,267125,2019-11-01,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 MURFREESBORO PIKE,37013.0,RED RIVER,4502,-86.633970,36.069130,2731 MURFREESBORO PIKE,None
20222,267126,2019-11-01,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 LONG AVE, NASHVILLE, TN 37206, UNITED STATES",37206.0,METRO,9508,-86.741242,36.169482,1621 LONG AVE,"NASHVILLE, TN 37206, UNITED STATES"
20223,267130,2019-11-01,Trash - Curbside/Alley Missed Pickup,missed several,"2943 WINDEMERE CIR, NASHVILLE, TN 37214, UNITE...",37214.0,RED RIVER,1502,-86.671647,36.185643,2943 WINDEMERE CIR,"NASHVILLE, TN 37214, UNITED STATES"
20224,267134,2019-11-01,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 MURFREESBORO PIKE, NASHVILLE, TN 37013, U...",37013.0,RED RIVER,4502,-86.620025,36.054637,3325 MURFREESBORO PIKE,"NASHVILLE, TN 37013, UNITED STATES"
20225,267137,2019-11-01,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 SOMERSET CT, NASHVILLE, TN 37217, UNITED S...",37217.0,RED RIVER,2505,-86.633331,36.083675,604 SOMERSET CT,"NASHVILLE, TN 37217, UNITED STATES"

In [25]:
cleantrash['Zip 2'] = cleantrash['Addy2'].str.extract(r'(\d{5})')

cleantrash.tail()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address,Addy2,Zip 2
20221,267125,2019-11-01,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 MURFREESBORO PIKE,37013.0,RED RIVER,4502,-86.633970,36.069130,2731 MURFREESBORO PIKE,None,NaN
20222,267126,2019-11-01,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 LONG AVE, NASHVILLE, TN 37206, UNITED STATES",37206.0,METRO,9508,-86.741242,36.169482,1621 LONG AVE,"NASHVILLE, TN 37206, UNITED STATES",37206
20223,267130,2019-11-01,Trash - Curbside/Alley Missed Pickup,missed several,"2943 WINDEMERE CIR, NASHVILLE, TN 37214, UNITE...",37214.0,RED RIVER,1502,-86.671647,36.185643,2943 WINDEMERE CIR,"NASHVILLE, TN 37214, UNITED STATES",37214
20224,267134,2019-11-01,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 MURFREESBORO PIKE, NASHVILLE, TN 37013, U...",37013.0,RED RIVER,4502,-86.620025,36.054637,3325 MURFREESBORO PIKE,"NASHVILLE, TN 37013, UNITED STATES",37013
20225,267137,2019-11-01,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 SOMERSET CT, NASHVILLE, TN 37217, UNITED S...",37217.0,RED RIVER,2505,-86.633331,36.083675,604 SOMERSET CT,"NASHVILLE, TN 37217, UNITED STATES",37217

In [26]:
cleantrash = cleantrash.drop(columns = ['Addy2', 'Incident Address'])
cleantrash.head()

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address,Zip 2
0,25270,2017-11-01,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",37207.0,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR,NaN
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,37218.0,RED RIVER,4202,-86.838103,36.213470,4028 CLARKSVILLE PIKE,NaN
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,37209.0,RED RIVER,4205,-86.885562,36.142923,6528 THUNDERBIRD DR,NaN
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,missed,37207.0,WASTE IND,2206,-86.789170,36.212652,2603 OLD MATTHEWS RD,NaN
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,37209.0,RED RIVER,4203,-86.874995,36.154861,604 CROLEY DR,NaN

In [27]:
cleantrash.tail()

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address,Zip 2
20221,267125,2019-11-01,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,37013.0,RED RIVER,4502,-86.633970,36.069130,2731 MURFREESBORO PIKE,NaN
20222,267126,2019-11-01,Trash - Curbside/Alley Missed Pickup,entire alley,37206.0,METRO,9508,-86.741242,36.169482,1621 LONG AVE,37206
20223,267130,2019-11-01,Trash - Curbside/Alley Missed Pickup,missed several,37214.0,RED RIVER,1502,-86.671647,36.185643,2943 WINDEMERE CIR,37214
20224,267134,2019-11-01,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,37013.0,RED RIVER,4502,-86.620025,36.054637,3325 MURFREESBORO PIKE,37013
20225,267137,2019-11-01,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,37217.0,RED RIVER,2505,-86.633331,36.083675,604 SOMERSET CT,37217

In [28]:
cleantrash.isna().sum()

Request Number       0
Date Opened          0
Request              0
Description         31
Zip Code            75
Trash Hauler       901
Trash Route        947
LONGITUDE           28
LATITUDE            28
Clean Address        9
Zip 2             6902
dtype: int64

In [29]:
cleantrash['Zip Code'] = cleantrash['Zip Code'].fillna(cleantrash['Zip 2'])
cleantrash.isna().sum()

Request Number       0
Date Opened          0
Request              0
Description         31
Zip Code            40
Trash Hauler       901
Trash Route        947
LONGITUDE           28
LATITUDE            28
Clean Address        9
Zip 2             6902
dtype: int64

In [30]:
cleantrash = cleantrash.drop(columns = ['Zip 2'])

In [31]:
trash.isna().sum()

Request Number        0
Date Opened           0
Request               0
Description          31
Incident Address      9
Zip Code             75
Trash Hauler        901
Trash Route         947
Council District     49
State Plan X         28
State Plan Y         28
LONGITUDE            28
LATITUDE             28
dtype: int64

In [32]:
cleantrash.nunique()

Request Number    20226
Date Opened         686
Request               4
Description       12879
Zip Code             49
Trash Hauler          3
Trash Route         173
LONGITUDE         14303
LATITUDE          14382
Clean Address     12381
dtype: int64

In [33]:
trash.nunique()

Request Number      20226
Date Opened           686
Request                 4
Description         12879
Incident Address    14121
Zip Code               28
Trash Hauler            4
Trash Route           173
Council District       35
State Plan X        14243
State Plan Y        14322
LONGITUDE           14303
LATITUDE            14382
dtype: int64

In [34]:
cleantrash['Zip Code'] = cleantrash['Zip Code'].astype('str')
cleantrash['Zip Code'] = cleantrash['Zip Code'].str.strip('.0')
cleantrash.head()

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address
0,25270,2017-11-01,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",37207,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,37218,RED RIVER,4202,-86.838103,36.213470,4028 CLARKSVILLE PIKE
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,37209,RED RIVER,4205,-86.885562,36.142923,6528 THUNDERBIRD DR
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,missed,37207,WASTE IND,2206,-86.789170,36.212652,2603 OLD MATTHEWS RD
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,37209,RED RIVER,4203,-86.874995,36.154861,604 CROLEY DR

In [35]:
cleantrash['Zip Code'] = cleantrash['Zip Code'].replace('nan', np.NaN)

In [36]:
cleantrash['Zip Code'].isna().sum()

40

In [37]:
cleantrash['Zip Code'].value_counts()

Zip Code
37013    2283
37211    2249
37205    1492
37209    1413
37215    1405
37207    1302
37115    1271
37206    1218
37208    1041
37214    1005
37218     983
37216     843
37217     834
37204     635
37212     602
3721      551
37203     395
3722      289
37027     170
37189      60
37221      48
37219      42
37201      35
37076       5
37138       5
37086       3
37213       1
37188       1
37174       1
37066       1
37228       1
30004       1
37129       1
Name: count, dtype: int64

In [38]:
cleantrash.head()

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address
0,25270,2017-11-01,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",37207,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,37218,RED RIVER,4202,-86.838103,36.213470,4028 CLARKSVILLE PIKE
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,37209,RED RIVER,4205,-86.885562,36.142923,6528 THUNDERBIRD DR
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,missed,37207,WASTE IND,2206,-86.789170,36.212652,2603 OLD MATTHEWS RD
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,37209,RED RIVER,4203,-86.874995,36.154861,604 CROLEY DR

In [39]:
cleantrash.Description = cleantrash.Description.str.upper()
cleantrash.head(3)

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address
0,25270,2017-11-01,Trash - Backdoor,"HOUSE WITH THE WHEEL CHAIR RAMP, THEY SHARE DR...",37207,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,CURB/TRASH MISS TUESDAY.,37218,RED RIVER,4202,-86.838103,36.213470,4028 CLARKSVILLE PIKE
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,CURB/TRASH MISS TUESDAY.,37209,RED RIVER,4205,-86.885562,36.142923,6528 THUNDERBIRD DR

In [40]:
cleantrash.isna().sum()

Request Number      0
Date Opened         0
Request             0
Description        31
Zip Code           40
Trash Hauler      901
Trash Route       947
LONGITUDE          28
LATITUDE           28
Clean Address       9
dtype: int64

In [41]:
cleantrash.loc[cleantrash.Request == 'Trash - Backdoor']

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address
0,25270,2017-11-01,Trash - Backdoor,"HOUSE WITH THE WHEEL CHAIR RAMP, THEY SHARE DR...",37207,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR
55,25692,2017-11-02,Trash - Backdoor,BACKDOOR/MISS FOR LAST FRIDAY. DOES NOT UNDERS...,37013,RED RIVER,3504,-86.618624,36.071107,3041 FIELDSTONE DR
63,25775,2017-11-02,Trash - Backdoor,MISSED TRASH PICKUP SAID HAS BEEN PICKING UP B...,37013,RED RIVER,4505,-86.670507,36.073590,4625 LONG BR
71,25802,2017-11-02,Trash - Backdoor,MISSED.,37013,RED RIVER,3404,-86.684493,36.061538,4828 CIMARRON WAY
78,25858,2017-11-03,Trash - Backdoor,MISSED- SHE SAID HER GRANDSON WAS OVER YESTERD...,3721,RED RIVER,1504,-86.704387,36.158919,2005 LEBANON PIKE
...,...,...,...,...,...,...,...,...,...,...
20165,266605,2019-10-31,Trash - Backdoor,HAS MISSED BACK DOOR TRASH PICK UP AGAIN/ ALSO...,37204,RED RIVER,3302,-86.801034,36.100482,4305 GRANNY WHITE PIKE
20167,266622,2019-10-31,Trash - Backdoor,MISSED BACKDOOR PICK UP HERE,37218,RED RIVER,3203,-86.863636,36.213257,4226 EATONS CREEK RD
20202,266912,2019-11-01,Trash - Backdoor,"MISSED MULTIPLE TIMES, PLEASE PICK UP",37214,RED RIVER,1505,-86.643325,36.181045,3110 LEBANON RD
20205,266944,2019-11-01,Trash - Backdoor,BACKDOOR MISS/ AGAIN THURSDAY,37204,METRO,9404,-86.777245,36.122378,812 HORNER AVE
20218,267110,2019-11-01,Trash - Backdoor,FRIDAY/PAID BACKDOOR TRASH,37214,RED RIVER,1503,-86.679639,36.181007,3105 FISHER DR

# Missed Pickup Calculation

In [42]:
cleantrash.head(1)

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address
0,25270,2017-11-01,Trash - Backdoor,"HOUSE WITH THE WHEEL CHAIR RAMP, THEY SHARE DR...",37207,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR

In [43]:
cleantrash.tail(1)

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address
20225,267137,2019-11-01,Trash - Curbside/Alley Missed Pickup,POSSIBLY OTHERS MISSED AS WELL,37217,RED RIVER,2505,-86.633331,36.083675,604 SOMERSET CT

In [44]:
cleantrash['Missed'] = False

In [45]:
cleantrash.columns

Index(['Request Number', 'Date Opened', 'Request', 'Description', 'Zip Code',
       'Trash Hauler', 'Trash Route', 'LONGITUDE', 'LATITUDE', 'Clean Address',
       'Missed'],
      dtype='object')

In [46]:
cleantrash.Request.value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [50]:
cleantrash.Description = cleantrash.Description.fillna('NULL')

In [54]:
for index, fields in cleantrash.iterrows():
    if fields.Request == 'Trash - Curbside/Alley Missed Pickup':
        cleantrash.loc[index, 'Missed'] = True
    elif re.match(r'.*MISS.*', fields.Description):
        cleantrash.loc[index, 'Missed'] = True

In [55]:
cleantrash.loc[cleantrash.Request == 'Trash - Backdoor']

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address,Missed
0,25270,2017-11-01,Trash - Backdoor,"HOUSE WITH THE WHEEL CHAIR RAMP, THEY SHARE DR...",37207,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR,False
55,25692,2017-11-02,Trash - Backdoor,BACKDOOR/MISS FOR LAST FRIDAY. DOES NOT UNDERS...,37013,RED RIVER,3504,-86.618624,36.071107,3041 FIELDSTONE DR,True
63,25775,2017-11-02,Trash - Backdoor,MISSED TRASH PICKUP SAID HAS BEEN PICKING UP B...,37013,RED RIVER,4505,-86.670507,36.073590,4625 LONG BR,True
71,25802,2017-11-02,Trash - Backdoor,MISSED.,37013,RED RIVER,3404,-86.684493,36.061538,4828 CIMARRON WAY,True
78,25858,2017-11-03,Trash - Backdoor,MISSED- SHE SAID HER GRANDSON WAS OVER YESTERD...,3721,RED RIVER,1504,-86.704387,36.158919,2005 LEBANON PIKE,True
...,...,...,...,...,...,...,...,...,...,...,...
20165,266605,2019-10-31,Trash - Backdoor,HAS MISSED BACK DOOR TRASH PICK UP AGAIN/ ALSO...,37204,RED RIVER,3302,-86.801034,36.100482,4305 GRANNY WHITE PIKE,True
20167,266622,2019-10-31,Trash - Backdoor,MISSED BACKDOOR PICK UP HERE,37218,RED RIVER,3203,-86.863636,36.213257,4226 EATONS CREEK RD,True
20202,266912,2019-11-01,Trash - Backdoor,"MISSED MULTIPLE TIMES, PLEASE PICK UP",37214,RED RIVER,1505,-86.643325,36.181045,3110 LEBANON RD,True
20205,266944,2019-11-01,Trash - Backdoor,BACKDOOR MISS/ AGAIN THURSDAY,37204,METRO,9404,-86.777245,36.122378,812 HORNER AVE,True
20218,267110,2019-11-01,Trash - Backdoor,FRIDAY/PAID BACKDOOR TRASH,37214,RED RIVER,1503,-86.679639,36.181007,3105 FISHER DR,False

In [58]:
cleantrash.Description = cleantrash.Description.replace('NULL', np.NaN)

In [59]:
cleantrash.isna().sum()

Request Number      0
Date Opened         0
Request             0
Description        31
Zip Code           40
Trash Hauler      901
Trash Route       947
LONGITUDE          28
LATITUDE           28
Clean Address       9
Missed              0
dtype: int64

# Short Zipcodes

In [60]:
cleantrash.head()

,Request Number,Date Opened,Request,Description,Zip Code,Trash Hauler,Trash Route,LONGITUDE,LATITUDE,Clean Address,Missed
0,25270,2017-11-01,Trash - Backdoor,"HOUSE WITH THE WHEEL CHAIR RAMP, THEY SHARE DR...",37207,RED RIVER,3205,-86.815392,36.217292,3817 CROUCH DR,False
1,25274,2017-11-01,Trash - Curbside/Alley Missed Pickup,CURB/TRASH MISS TUESDAY.,37218,RED RIVER,4202,-86.838103,36.213470,4028 CLARKSVILLE PIKE,True
2,25276,2017-11-01,Trash - Curbside/Alley Missed Pickup,CURB/TRASH MISS TUESDAY.,37209,RED RIVER,4205,-86.885562,36.142923,6528 THUNDERBIRD DR,True
3,25307,2017-11-01,Trash - Curbside/Alley Missed Pickup,MISSED,37207,WASTE IND,2206,-86.789170,36.212652,2603 OLD MATTHEWS RD,True
4,25312,2017-11-01,Trash - Curbside/Alley Missed Pickup,MISSED THE EVEN SIDE OF THE ROAD.,37209,RED RIVER,4203,-86.874995,36.154861,604 CROLEY DR,True

In [70]:
# THIS IS BROKEN & UNFINISHED

for index, fields in cleantrash.iterrows():
    try:
        if len(fields['Zip Code']) < 5:
            addy = cleantrash.loc[index, 'Clean Address']
            matchers = cleantrash.loc[cleantrash['Clean Address'] == addy]
            if len(matchers['Zip Code'].max()) == 5:
                cleantrash[index, 'Zip Code'] = matchers['Zip Code'].max()
    except (AttributeError, TypeError):
        continue

In [74]:
cleantrash.loc[cleantrash['Zip Code'] == r'\d{5}']

Empty DataFrame
Columns: [Request Number, Date Opened, Request, Description, Zip Code, Trash Hauler, Trash Route, LONGITUDE, LATITUDE, Clean Address, Missed, (18564, Zip Code)]
Index: []